apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-rollingupdate
  labels:
    app: redis-app-rollingupdate
spec:
  replicas: 10
  strategy:
        type: RollingUpdate
        rollingUpdate:
           maxSurge: 25%
           maxUnavailable: 25%      
  selector:
    matchLabels:
      app: redis-app-rollingupdate
  template:
    metadata:
      labels:
        app: redis-app-rollingupdate
    spec:
      containers:
        - name: redis
          image: redis:latest