apiVersion: v1
kind: Pod
metadata:
  name: inject-config-via-volume
spec:
  containers:
    - name: consuming-container
      image: k8s.gcr.io/busybox      
      command: [ "/bin/sh","-c","cat /etc/config/keys" ]
      volumeMounts:      
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: mysql-config-volume
        items:
        - key: DB_NAME
          path: keys
  restartPolicy: Never