apiVersion: v1
kind: Pod
metadata:
  name: constraints-mem-exceeding
spec:
  containers:
  - name: constraints-mem-exceeding
    image: nginx
    resources:
      limits:
        memory: "1.5Gi"
      requests:
        memory: "800Mi"